[package]
name = "henze-ds-web"
version = "0.1.0"
edition = "2021"

[dependencies]
henze_ds = { path = "../henze-ds" }
rocket = { version = "0.5.1", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
tera = "1.19.1"